config/routes.rb
RailsFootballManager::Application.routes.draw do

  root 'football_manager#index'

  get '/footballmanager' => 'football_manager#index'
  get '/find' => 'players#find', as: 'find'

  get '/transfer' => 'transfer#index'
  post '/transfer' => 'transfer#transfer_player'

  resources :games
  resources :coaches
  resources :players
  resources :teams
end

app/controllers/football_manager_controller.rb
class FootballManagerController < ApplicationController
	def index
		@teams = Team.all
  end
end

app/views/football_manager/index.html.erb
	<% if flash[:notice] %>
		<div class="notice"><%= flash[:notice] %></div>
		<br/>
	<% end %>

	<%= link_to teams_path, class: 'tableHeader' do %>
	<h2 class='tableHeader r'>Teams</h2>
	<% end %><br/>

	<%= link_to games_path,class: 'tableHeader' do %>
	<h2 class='tableHeader l'>Games</h2>
	<% end %><br/>

	<%= link_to players_path, class: 'tableHeader', id: 'players_id' do %>
	<h2 class='tableHeader r'>Players and Coaches</h2>
	<% end %><br/>

	<%= link_to transfer_path, class: 'tableHeader'  do %>
	<h2 class='tableHeader l'>Transfer Players</h2>
	<% end %><br/>


	<table id=searchTable>
	<tr>
		<%= form_tag(players_path, method: 'get') do %>
			<td>
			<%= text_field_tag :search, nil, placeholder: "Search by name or number", id: 'searchField', class: 'roundUpsize'  %>
		</td>
		<td>
			<%= button_tag 'Search', id: 'searchButton', class: 'roundUpsize button'%>
		</td>
		<% end %>

		<td id=spacer>
		</td>


		<%= form_tag("/find", method: 'get') do %>
			<td>
				<%= text_field_tag :name, nil, placeholder: "Enter player name", id: 'nameField', class: 'roundUpsize'  %>
				<%= text_field_tag :number, nil, placeholder: "Enter player #", id: 'numberField', class: 'roundUpsize'  %>
			</td>
			<td>
				<%= button_tag 'Find', class: 'roundUpsize button'%>
			</td>
		<% end %>
	</tr>
	</table>
<script>
    $('.r').addClass('animated bounceInLeft');
    $('.l').addClass('animated lightSpeedIn');
    $('.button').addClass('animated rubberBand');
</script>