config/routes.rb
RailsFootballManager::Application.routes.draw do

  root 'football_manager#index'

  get '/footballmanager' => 'football_manager#index'
  get '/find' => 'players#find', as: 'find'

  get '/transfer' => 'transfer#index'
  post '/transfer' => 'transfer#transfer_player'

  resources :games
  resources :coaches
  resources :players
  resources :teams
end

app/models/game.rb
class Game < ActiveRecord::Base
	belongs_to :home_team, class_name: 'Team' , foreign_key: 'home_team_id'
	belongs_to :away_team, class_name: 'Team', foreign_key: 'away_team_id'
	validates :home_team_score, :away_team_score, :home_team_id, :away_team_id, presence: true
	validate :home_and_away_teams_are_different
	validate :date_not_future
	validates :home_team_score, :away_team_score, :numericality => { :greater_than_or_equal_to => 0 }, :allow_blank => true

	def home_and_away_teams_are_different
		if home_team_id == away_team_id
			errors.add(:away_team_id, "must be different from home team")
		end
	end


	def date_not_future
		if date > Date.current
			errors.add(:date, "cannot be in the future")
		end
	end

	def winner
		return home_team.name if home_team_score > away_team_score
		return away_team.name if home_team_score < away_team_score
		return 'tie' if home_team_score == away_team_score
	end

	def result(team)
		if winner == 'tie'
			return 'T'
		elsif winner == team
			return 'W'
		else
			return 'L'
		end
	end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  def index
    @games = Game.all
  end

  def show
  end

  def new
    @game = Game.new
  end

  def edit
  end

  def create
    @game = Game.new(game_params)
      if @game.save
        redirect_to games_url, notice: 'Game was successfully created.'
      else
        render action: 'new'
      end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
      if @game.update(game_params)
        redirect_to @game, notice: 'Game was successfully updated.'
      else
        render action: 'edit'
      end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    redirect_to games_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
      rescue ActiveRecord::RecordNotFound
      flash[:notice] = "Sorry, that page does not exist"
      redirect_to root_path
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:home_team_id, :away_team_id, :home_team_score, :away_team_score, :date)
    end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<div class='centered'>
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation" class='centered'>
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |msg| %>
        <%= msg %><br/>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field" id = 'home_team'>
    <%= f.label :home_team_id %><br>
    <%= f.collection_select(:home_team_id, Team.all, :id, :name)%>
  </div>
  <div class="field" id = 'away_team'>
    <%= f.label :away_team_id %><br>
    <%= f.collection_select(:away_team_id, Team.all, :id, :name, {}, {:class=>'roundUpsize'})%>
  </div>
  <div class="field">
    <%= f.label :home_team_score %><br>
    <%= f.text_field :home_team_score, :class => 'roundUpsize' %>
  </div>
  <div class="field">
    <%= f.label :away_team_score %><br>
    <%= f.text_field :away_team_score, :class => 'roundUpsize' %>
  </div>
  <div class="date">
    <%= f.label :date %><br>
    <%= f.date_select :date, :class => 'roundUpsize' %>
  </div>
  <div class="actions verticalSpace">
    <%= f.submit 'Create Game', :class =>'button', id: 'wideButton' %>
  </div>
<% end %>
</div>

app/views/games/_game_table.html.erb
<h2 class='tableHeader'>Games Played</h2>

<table class = 'hover-table sortable centerTable'>
  <thead>
    <tr>
      <th>Game</th>
      <th class='hidden'>Result</th>
      <th>Date</th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.home_team.name %>(<%= game.home_team_score %>) vs <%= game.away_team.name %>(<%= game.away_team_score %>)</td>
        <td class='hidden'><%= game.result(@team_name) %></td>
        <td><%= game.date %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/games/edit.html.erb
<h1>Editing game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<p id="notice"><%= notice %></p>

 <%= render 'games/game_table' %>

<div class='centered verticalSpace'>
<%= link_to 'New Game', new_game_path, class: 'button visited', name: 'New Game' %>
</div>
<script>
    $('.button').addClass('animated shake');
</script>

app/views/games/new.html.erb
<h2>New game</h2>

<%= render 'form' %>

<div class='centered'>
<%= link_to 'Back', games_path %>
</div>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Home team:</strong>
  <%= @game.home_team.name %>
</p>

<p>
  <strong>Away team:</strong>
  <%= @game.away_team.name %>
</p>

<p>
  <strong>Home team score:</strong>
  <%= @game.home_team_score %>
</p>

<p>
  <strong>Away team score:</strong>
  <%= @game.away_team_score %>
</p>

<p>
  <strong>Date:</strong>
  <%= @game.date %>
</p>

<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>